// Generated by gencpp from file senseglove_shared_resources/Calibrate.msg
// DO NOT EDIT!


#ifndef SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATE_H
#define SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATE_H

#include <ros/service_traits.h>


#include <senseglove_shared_resources/CalibrateRequest.h>
#include <senseglove_shared_resources/CalibrateResponse.h>


namespace senseglove_shared_resources
{

struct Calibrate
{

typedef CalibrateRequest Request;
typedef CalibrateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Calibrate
} // namespace senseglove_shared_resources


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::senseglove_shared_resources::Calibrate > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::senseglove_shared_resources::Calibrate&) { return value(); }
};

template<>
struct DataType< ::senseglove_shared_resources::Calibrate > {
  static const char* value()
  {
    return "senseglove_shared_resources/Calibrate";
  }

  static const char* value(const ::senseglove_shared_resources::Calibrate&) { return value(); }
};


// service_traits::MD5Sum< ::senseglove_shared_resources::CalibrateRequest> should match
// service_traits::MD5Sum< ::senseglove_shared_resources::Calibrate >
template<>
struct MD5Sum< ::senseglove_shared_resources::CalibrateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::senseglove_shared_resources::Calibrate >::value();
  }
  static const char* value(const ::senseglove_shared_resources::CalibrateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::senseglove_shared_resources::CalibrateRequest> should match
// service_traits::DataType< ::senseglove_shared_resources::Calibrate >
template<>
struct DataType< ::senseglove_shared_resources::CalibrateRequest>
{
  static const char* value()
  {
    return DataType< ::senseglove_shared_resources::Calibrate >::value();
  }
  static const char* value(const ::senseglove_shared_resources::CalibrateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::senseglove_shared_resources::CalibrateResponse> should match
// service_traits::MD5Sum< ::senseglove_shared_resources::Calibrate >
template<>
struct MD5Sum< ::senseglove_shared_resources::CalibrateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::senseglove_shared_resources::Calibrate >::value();
  }
  static const char* value(const ::senseglove_shared_resources::CalibrateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::senseglove_shared_resources::CalibrateResponse> should match
// service_traits::DataType< ::senseglove_shared_resources::Calibrate >
template<>
struct DataType< ::senseglove_shared_resources::CalibrateResponse>
{
  static const char* value()
  {
    return DataType< ::senseglove_shared_resources::Calibrate >::value();
  }
  static const char* value(const ::senseglove_shared_resources::CalibrateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATE_H
