// Generated by gencpp from file senseglove_shared_resources/CalibrateRequest.msg
// DO NOT EDIT!


#ifndef SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATEREQUEST_H
#define SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace senseglove_shared_resources
{
template <class ContainerAllocator>
struct CalibrateRequest_
{
  typedef CalibrateRequest_<ContainerAllocator> Type;

  CalibrateRequest_()
    : name()  {
    }
  CalibrateRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrateRequest_

typedef ::senseglove_shared_resources::CalibrateRequest_<std::allocator<void> > CalibrateRequest;

typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateRequest > CalibrateRequestPtr;
typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateRequest const> CalibrateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator1> & lhs, const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator1> & lhs, const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace senseglove_shared_resources

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "senseglove_shared_resources/CalibrateRequest";
  }

  static const char* value(const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A service to request calibration\n"
"\n"
"string name  # Optional: name for this calibration profile\n"
;
  }

  static const char* value(const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibrateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::senseglove_shared_resources::CalibrateRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATEREQUEST_H
