// Generated by gencpp from file senseglove_shared_resources/CalibrateResponse.msg
// DO NOT EDIT!


#ifndef SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATERESPONSE_H
#define SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace senseglove_shared_resources
{
template <class ContainerAllocator>
struct CalibrateResponse_
{
  typedef CalibrateResponse_<ContainerAllocator> Type;

  CalibrateResponse_()
    : success(false)  {
    }
  CalibrateResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrateResponse_

typedef ::senseglove_shared_resources::CalibrateResponse_<std::allocator<void> > CalibrateResponse;

typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateResponse > CalibrateResponsePtr;
typedef boost::shared_ptr< ::senseglove_shared_resources::CalibrateResponse const> CalibrateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator1> & lhs, const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator1> & lhs, const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace senseglove_shared_resources

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "senseglove_shared_resources/CalibrateResponse";
  }

  static const char* value(const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibrateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::senseglove_shared_resources::CalibrateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEGLOVE_SHARED_RESOURCES_MESSAGE_CALIBRATERESPONSE_H
