// Generated by gencpp from file senseglove_shared_resources/KinematicsVect3D.msg
// DO NOT EDIT!


#ifndef SENSEGLOVE_SHARED_RESOURCES_MESSAGE_KINEMATICSVECT3D_H
#define SENSEGLOVE_SHARED_RESOURCES_MESSAGE_KINEMATICSVECT3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace senseglove_shared_resources
{
template <class ContainerAllocator>
struct KinematicsVect3D_
{
  typedef KinematicsVect3D_<ContainerAllocator> Type;

  KinematicsVect3D_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  KinematicsVect3D_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicsVect3D_

typedef ::senseglove_shared_resources::KinematicsVect3D_<std::allocator<void> > KinematicsVect3D;

typedef boost::shared_ptr< ::senseglove_shared_resources::KinematicsVect3D > KinematicsVect3DPtr;
typedef boost::shared_ptr< ::senseglove_shared_resources::KinematicsVect3D const> KinematicsVect3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator1> & lhs, const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator1> & lhs, const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace senseglove_shared_resources

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "senseglove_shared_resources/KinematicsVect3D";
  }

  static const char* value(const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinematicsVect3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::senseglove_shared_resources::KinematicsVect3D_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEGLOVE_SHARED_RESOURCES_MESSAGE_KINEMATICSVECT3D_H
