# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from senseglove_shared_resources/FingerDistanceFloats.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class FingerDistanceFloats(genpy.Message):
  _md5sum = "645d53f7de8b68c040fc08d5668ceb96"
  _type = "senseglove_shared_resources/FingerDistanceFloats"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float64 th_ff  # thumb to index finger
std_msgs/Float64 th_mf  # thumb to middle finger
std_msgs/Float64 th_rf  # thumb to ring finger
std_msgs/Float64 th_lf  # future when pink is on shadow hand

================================================================================
MSG: std_msgs/Float64
float64 data"""
  __slots__ = ['th_ff','th_mf','th_rf','th_lf']
  _slot_types = ['std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       th_ff,th_mf,th_rf,th_lf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FingerDistanceFloats, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.th_ff is None:
        self.th_ff = std_msgs.msg.Float64()
      if self.th_mf is None:
        self.th_mf = std_msgs.msg.Float64()
      if self.th_rf is None:
        self.th_rf = std_msgs.msg.Float64()
      if self.th_lf is None:
        self.th_lf = std_msgs.msg.Float64()
    else:
      self.th_ff = std_msgs.msg.Float64()
      self.th_mf = std_msgs.msg.Float64()
      self.th_rf = std_msgs.msg.Float64()
      self.th_lf = std_msgs.msg.Float64()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.th_ff.data, _x.th_mf.data, _x.th_rf.data, _x.th_lf.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.th_ff is None:
        self.th_ff = std_msgs.msg.Float64()
      if self.th_mf is None:
        self.th_mf = std_msgs.msg.Float64()
      if self.th_rf is None:
        self.th_rf = std_msgs.msg.Float64()
      if self.th_lf is None:
        self.th_lf = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.th_ff.data, _x.th_mf.data, _x.th_rf.data, _x.th_lf.data,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.th_ff.data, _x.th_mf.data, _x.th_rf.data, _x.th_lf.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.th_ff is None:
        self.th_ff = std_msgs.msg.Float64()
      if self.th_mf is None:
        self.th_mf = std_msgs.msg.Float64()
      if self.th_rf is None:
        self.th_rf = std_msgs.msg.Float64()
      if self.th_lf is None:
        self.th_lf = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.th_ff.data, _x.th_mf.data, _x.th_rf.data, _x.th_lf.data,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
